# Generated by Django 6.0.3 on 2026-03-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('tag', models.CharField(choices=[('all', 'All'), ('decoration', 'Decoration'), ('floral', 'Floral'), ('stage', 'Stage'), ('planning', 'Planning'), ('reception', 'Reception')], default='all', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
