# Generated by Django 6.0.3 on 2026-03-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='is_hero',
            field=models.BooleanField(default=False, help_text='Set to True if this is the main hero background video'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL for the video (e.g. from a CDN or public link)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='tag',
            field=models.CharField(choices=[('all', 'All'), ('decoration', 'Decoration'), ('floral', 'Floral'), ('stage', 'Stage'), ('planning', 'Planning'), ('reception', 'Reception'), ('hero', 'Hero Video')], default='all', max_length=50),
        ),
    ]
